version: 2
jobs:
  build-node9:
    working_directory: ~/docs
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Install yarn
          command: 'curl -o- -L https://yarnpkg.com/install.sh | bash && export PATH="$HOME/.yarn/bin:$PATH" && yarn config set cache-folder $HOME/.cache/yarn'
      - restore_cache:
          key: core-node9-{{ checksum "package.json" }}-1
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: core-node9-{{ checksum "package.json" }}-1
          paths:
            -  ./node_modules
      - run:
          name: Yarn build
          command: yarn build

  build-node10:
    working_directory: ~/docs
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install yarn
          command: 'curl -o- -L https://yarnpkg.com/install.sh | bash && export PATH="$HOME/.yarn/bin:$PATH" && yarn config set cache-folder $HOME/.cache/yarn'
      - restore_cache:
          key: core-node10-{{ checksum "package.json" }}-1
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: core-node10-{{ checksum "package.json" }}-1
          paths:
            -  ./node_modules
      - run:
          name: Yarn build
          command: yarn build

workflows:
  version: 2
  build:
    jobs:
      - build-node9
      - build-node10
